name: Build Ubuntu Touch

on:
  workflow_dispatch:

env:
  ADAPTATION_TOOLS_BRANCH: main
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Add Dependencies 
         run: |
            sudo apt update
            sudo apt install -y --no-install-recommends bc bison build-essential ca-certificates cpio curl fakeroot flex git kmod libelf-dev libssl-dev libtinfo5 lz4 python2 python3 sudo unzip wget xz-utils pahole libbpf-dev img2simg jq sudo wget xz-utils zstd
  
       - name: Building 
         run: |
             git clone -b $ADAPTATION_TOOLS_BRANCH https://gitlab.com/hasajapathirana2011/halium-generic-adaptation-build-tools.git build
             sudo chmod 644 overlay/system/etc/deviceinfo/devices/gtowifi.yaml
             ls
             ./build/build.sh
             ./build/prepare-fake-ota.sh ./out/device_gtowifi_usrmerge.tar.xz ota
             ./build/system-image-from-ota.sh ota/ubuntu_command images
             mv images/rootfs.img images/ubuntu.img
             ls -l images/
             pwd
             zstd --ultra -22 -T0 images/ubuntu.img
             rm -f images/ubuntu.img

       - name: Patch boot.img 
         run: |
             mv images/boot.img images/temp.img
             curl -L https://raw.githubusercontent.com/GalaxyA20s/A20s-Fix-Bootable-Image/refs/heads/main/fix_bootable_image.py -o fix_bootable_image.py
             python3 fix_bootable_image.py images/temp.img images/boot.img

        
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name:  Ubuntu Touch Rootfs and Boot Image for gtowifi  
          files: |
           /home/runner/work/ubuntu-touch-galaxy-tab-a8-2019/ubuntu-touch-galaxy-tab-a8-2019/images/boot.img
           /home/runner/work/ubuntu-touch-galaxy-tab-a8-2019/ubuntu-touch-galaxy-tab-a8-2019/images/ubuntu.img.zst
  
  
